version: '3'
services:
  mysql:
    image: mysql:8
    container_name: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456 #设置root帐号密码
    ports:
      - 3306:3306
    volumes:
      - /mydata/mysql/data/db:/f/dockerData/gdc/report/mysql/data #数据文件挂载
      - /mydata/mysql/data/conf:/f/dockerData/gdc/report/mysql/conf/conf.d #配置文件挂载
      - /mydata/mysql/log:/f/dockerData/gdc/report/mysql/log #日志文件挂载
  redis:
    image: redis:5
    container_name: redis
    command: redis-server --appendonly yes
    volumes:
      - /mydata/redis/data:/f/dockerData/gdc/report/redis/data #数据文件挂载
    ports:
      - 6379:6379