spring:
  profiles:
    active: dev #默认为开发环境
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 10MB #限制文件上传大小为10M
  resource:
    static-locations: classpath:/static/,classpath:/public/
  #配置freemarker
  freemarker:
    # 设置模板后缀名
    suffix: .ftl
    # 设置文档类型
    content-type: text/html
    # 设置页面编码格式
    charset: UTF-8
    # 设置页面缓存
    cache: false
    prefer-file-system-access: false
    # 设置ftl文件路径
    template-loader-path:
      - classpath:/templates

#配置mapper xml文件的路径
mybatis-plus:
  mapper-locations: classpath*:org/jeecg/modules/**/xml/*Mapper.xml

jeecg:
  #local\minio\alioss
  uploadType: local
  path:
    upload:/opt/upload
  #阿里云oss
  oss:
    endpoint:
    accessKey:
    secretKey:
    bucketName:
    staticDomain:
  #minio文件
  minio:
    minio_url:
    minio_name:
    minio_pass:
    bucketName:



